"""Public accessible chart presentation package."""

from app.ui.charts.contracts import (
    CONTRACT_VERSION,
    MAX_POINTS_PER_SERIES,
    MAX_RENDER_POINTS,
    MAX_SERIES,
    ChartAxis,
    ChartAxisScale,
    ChartColorRole,
    ChartKind,
    ChartLineStyle,
    ChartMarker,
    ChartPoint,
    ChartSelection,
    ChartSelectionCause,
    ChartSeries,
    ChartSourceEvidence,
    ChartSpec,
    ChartState,
    ChartViewport,
)
from app.ui.charts.exporter import (
    MAX_DEVICE_SCALE,
    MAX_EXPORT_DIMENSION,
    MAX_PHYSICAL_PIXELS,
    MIN_EXPORT_HEIGHT,
    MIN_EXPORT_WIDTH,
    export_chart_csv,
    export_chart_json,
    export_chart_png,
    export_chart_svg,
)
from app.ui.charts.render_plan import (
    ChartRenderPlan,
    GeometryPoint,
    GeometryRect,
    RenderLineSegment,
    RenderMark,
    RenderTick,
    normalize_chart,
)
from app.ui.charts.table_model import ChartTableModel, ChartTableRow
from app.ui.charts.widget import ChartCanvas, ChartWidget


__all__ = [
    "CONTRACT_VERSION",
    "MAX_DEVICE_SCALE",
    "MAX_EXPORT_DIMENSION",
    "MAX_PHYSICAL_PIXELS",
    "MAX_POINTS_PER_SERIES",
    "MAX_RENDER_POINTS",
    "MAX_SERIES",
    "MIN_EXPORT_HEIGHT",
    "MIN_EXPORT_WIDTH",
    "ChartAxis",
    "ChartAxisScale",
    "ChartCanvas",
    "ChartColorRole",
    "ChartKind",
    "ChartLineStyle",
    "ChartMarker",
    "ChartPoint",
    "ChartRenderPlan",
    "ChartSelection",
    "ChartSelectionCause",
    "ChartSeries",
    "ChartSourceEvidence",
    "ChartSpec",
    "ChartState",
    "ChartTableModel",
    "ChartTableRow",
    "ChartViewport",
    "ChartWidget",
    "GeometryPoint",
    "GeometryRect",
    "RenderLineSegment",
    "RenderMark",
    "RenderTick",
    "export_chart_csv",
    "export_chart_json",
    "export_chart_png",
    "export_chart_svg",
    "normalize_chart",
]
